-- Stripe integration: link companies to Stripe customers, mirror payments & subscriptions.

alter table public.companies
    add column if not exists stripe_customer_id text;

create unique index if not exists companies_stripe_customer_id_key
    on public.companies (stripe_customer_id)
    where stripe_customer_id is not null;

create table if not exists public.payments (
    id bigint generated by default as identity primary key,
    stripe_event_id text not null unique,
    stripe_object_id text not null,
    stripe_customer_id text,
    company_id bigint references public.companies(id) on delete set null,
    deal_id bigint references public.deals(id) on delete set null,
    type text not null,
    status text,
    amount bigint not null,
    amount_refunded bigint not null default 0,
    currency text not null default 'eur',
    description text,
    invoice_number text,
    hosted_invoice_url text,
    receipt_url text,
    occurred_at timestamptz not null,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists payments_company_id_idx on public.payments (company_id);
create index if not exists payments_deal_id_idx on public.payments (deal_id);
create index if not exists payments_stripe_customer_id_idx on public.payments (stripe_customer_id);
create index if not exists payments_occurred_at_idx on public.payments (occurred_at desc);

create table if not exists public.subscriptions (
    id bigint generated by default as identity primary key,
    stripe_subscription_id text not null unique,
    stripe_customer_id text not null,
    company_id bigint references public.companies(id) on delete set null,
    status text not null,
    product_name text,
    amount bigint,
    currency text default 'eur',
    recurring_interval text,
    current_period_start timestamptz,
    current_period_end timestamptz,
    cancel_at_period_end boolean not null default false,
    canceled_at timestamptz,
    started_at timestamptz,
    metadata jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now(),
    created_at timestamptz not null default now()
);

create index if not exists subscriptions_company_id_idx on public.subscriptions (company_id);
create index if not exists subscriptions_stripe_customer_id_idx on public.subscriptions (stripe_customer_id);
create index if not exists subscriptions_status_idx on public.subscriptions (status);

alter table public.payments enable row level security;
create policy "Enable read for authenticated" on public.payments for select to authenticated using (true);
create policy "Enable insert for service role" on public.payments for insert to service_role with check (true);
create policy "Enable update for service role" on public.payments for update to service_role using (true) with check (true);
create policy "Enable delete for service role" on public.payments for delete to service_role using (true);

alter table public.subscriptions enable row level security;
create policy "Enable read for authenticated" on public.subscriptions for select to authenticated using (true);
create policy "Enable insert for service role" on public.subscriptions for insert to service_role with check (true);
create policy "Enable update for service role" on public.subscriptions for update to service_role using (true) with check (true);
create policy "Enable delete for service role" on public.subscriptions for delete to service_role using (true);

grant select on table public.payments to authenticated;
grant all on table public.payments to service_role;
grant all on sequence public.payments_id_seq to service_role;

grant select on table public.subscriptions to authenticated;
grant all on table public.subscriptions to service_role;
grant all on sequence public.subscriptions_id_seq to service_role;

-- Keep subscriptions.updated_at fresh
create or replace function public.subscriptions_set_updated_at()
returns trigger language plpgsql as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists subscriptions_updated_at on public.subscriptions;
create trigger subscriptions_updated_at
    before update on public.subscriptions
    for each row execute function public.subscriptions_set_updated_at();
