-- Scoring system: lead_source, score_rules, score_events, score_targets, triggers, views.

-- 1. Add lead_source to existing tables
alter table public.companies  add column if not exists lead_source text not null default 'unknown';
alter table public.contacts   add column if not exists lead_source text not null default 'unknown';
alter table public.deals      add column if not exists lead_source text not null default 'unknown';

-- 2. Scoring tables
create table if not exists public.score_rules (
    id bigint generated by default as identity primary key,
    code text not null unique,
    domain text not null check (domain in ('sales', 'delivery')),
    label text not null,
    weight_class text not null check (weight_class in ('acquisition', 'execution', 'revenue', 'none')),
    base_points numeric not null,
    enabled boolean not null default true,
    config jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.score_events (
    id bigint generated by default as identity primary key,
    sales_id bigint not null references public.sales(id) on delete cascade,
    domain text not null check (domain in ('sales', 'delivery')),
    rule_code text not null,
    entity_type text not null,
    entity_id bigint,
    raw_points numeric not null,
    weight numeric not null default 1,
    points numeric not null,
    occurred_at timestamptz not null default now(),
    period_day date not null default current_date,
    idempotency_key text not null unique,
    metadata jsonb not null default '{}'::jsonb
);

create index if not exists score_events_sales_id_idx  on public.score_events using btree (sales_id);
create index if not exists score_events_period_day_idx on public.score_events using btree (period_day);
create index if not exists score_events_domain_idx     on public.score_events using btree (domain);

create table if not exists public.score_targets (
    id bigint generated by default as identity primary key,
    domain text not null check (domain in ('sales', 'delivery')),
    period text not null check (period in ('week', 'month', 'quarter')),
    target_score numeric not null,
    unique (domain, period)
);

-- 3. RLS
alter table public.score_rules   enable row level security;
alter table public.score_events  enable row level security;
alter table public.score_targets enable row level security;

do $$ begin
    if not exists (select 1 from pg_policies where tablename = 'score_rules' and policyname = 'Enable read for authenticated') then
        create policy "Enable read for authenticated" on public.score_rules for select to authenticated using (true);
    end if;
    if not exists (select 1 from pg_policies where tablename = 'score_rules' and policyname = 'Enable insert for admins') then
        create policy "Enable insert for admins" on public.score_rules for insert to authenticated with check (public.is_admin());
    end if;
    if not exists (select 1 from pg_policies where tablename = 'score_rules' and policyname = 'Enable update for admins') then
        create policy "Enable update for admins" on public.score_rules for update to authenticated using (public.is_admin()) with check (public.is_admin());
    end if;

    if not exists (select 1 from pg_policies where tablename = 'score_events' and policyname = 'Enable read for authenticated') then
        create policy "Enable read for authenticated" on public.score_events for select to authenticated using (true);
    end if;
    if not exists (select 1 from pg_policies where tablename = 'score_events' and policyname = 'Enable insert for authenticated') then
        create policy "Enable insert for authenticated" on public.score_events for insert to authenticated with check (true);
    end if;

    if not exists (select 1 from pg_policies where tablename = 'score_targets' and policyname = 'Enable read for authenticated') then
        create policy "Enable read for authenticated" on public.score_targets for select to authenticated using (true);
    end if;
    if not exists (select 1 from pg_policies where tablename = 'score_targets' and policyname = 'Enable insert for admins') then
        create policy "Enable insert for admins" on public.score_targets for insert to authenticated with check (public.is_admin());
    end if;
    if not exists (select 1 from pg_policies where tablename = 'score_targets' and policyname = 'Enable update for admins') then
        create policy "Enable update for admins" on public.score_targets for update to authenticated using (public.is_admin()) with check (public.is_admin());
    end if;
end $$;

-- 4. Grants
grant all on table public.score_rules   to anon, authenticated, service_role;
grant all on table public.score_events  to anon, authenticated, service_role;
grant all on table public.score_targets to anon, authenticated, service_role;
grant all on sequence public.score_rules_id_seq   to anon, authenticated, service_role;
grant all on sequence public.score_events_id_seq  to anon, authenticated, service_role;
grant all on sequence public.score_targets_id_seq to anon, authenticated, service_role;

-- 5. Helper functions
create or replace function public.resolve_source_weight(p_lead_source text)
returns numeric language plpgsql immutable as $$
begin
    return case p_lead_source
        when 'outbound'       then 1.0
        when 'referral'       then 0.8
        when 'partner'        then 0.7
        when 'manual'         then 0.6
        when 'email_campaign' then 0.5
        when 'seo'            then 0.3
        when 'other'          then 0.5
        else 0.5
    end;
end;
$$;

create or replace function public.resolve_lead_source(
    p_contact_id bigint default null,
    p_company_id bigint default null,
    p_deal_id    bigint default null
) returns text language plpgsql stable as $$
declare
    v_source text;
begin
    if p_deal_id is not null then
        select lead_source into v_source from public.deals where id = p_deal_id;
        if v_source is not null and v_source <> 'unknown' then return v_source; end if;
    end if;
    if p_contact_id is not null then
        select lead_source into v_source from public.contacts where id = p_contact_id;
        if v_source is not null and v_source <> 'unknown' then return v_source; end if;
    end if;
    if p_company_id is not null then
        select lead_source into v_source from public.companies where id = p_company_id;
        if v_source is not null and v_source <> 'unknown' then return v_source; end if;
    end if;
    return 'unknown';
end;
$$;

create or replace function public.is_meaningful_note(p_text text, p_attachments jsonb[])
returns boolean language plpgsql immutable as $$
begin
    return (length(coalesce(p_text, '')) >= 80)
        or (p_attachments is not null and array_length(p_attachments, 1) > 0);
end;
$$;

create or replace function public.emit_score_event(
    p_sales_id        bigint,
    p_domain          text,
    p_rule_code       text,
    p_entity_type     text,
    p_entity_id       bigint,
    p_raw_points      numeric,
    p_weight          numeric,
    p_idempotency_key text,
    p_metadata        jsonb default '{}'::jsonb
) returns void language plpgsql as $$
begin
    insert into public.score_events (
        sales_id, domain, rule_code, entity_type, entity_id,
        raw_points, weight, points, idempotency_key, metadata
    ) values (
        p_sales_id, p_domain, p_rule_code, p_entity_type, p_entity_id,
        p_raw_points, p_weight, round(p_raw_points * p_weight, 2),
        p_idempotency_key, p_metadata
    ) on conflict (idempotency_key) do nothing;
end;
$$;

-- 6. Scoring trigger functions
create or replace function public.score_on_company_insert() returns trigger language plpgsql as $$
declare
    v_useful int := 0;
    v_weight numeric;
begin
    if NEW.website       is not null then v_useful := v_useful + 1; end if;
    if NEW.phone_number  is not null then v_useful := v_useful + 1; end if;
    if NEW.sector        is not null then v_useful := v_useful + 1; end if;
    if NEW.description   is not null then v_useful := v_useful + 1; end if;
    if NEW.context_links is not null then v_useful := v_useful + 1; end if;
    if v_useful >= 2 and NEW.sales_id is not null then
        v_weight := public.resolve_source_weight(NEW.lead_source);
        perform public.emit_score_event(
            NEW.sales_id, 'sales', 'sales.company_created_qualified',
            'company', NEW.id, 2, v_weight,
            'sales.company_created_qualified:company:' || NEW.id
        );
    end if;
    return NEW;
end;
$$;

create or replace function public.score_on_contact_insert() returns trigger language plpgsql as $$
declare
    v_weight numeric;
begin
    if NEW.sales_id is null then return NEW; end if;
    if jsonb_array_length(coalesce(NEW.email_jsonb, '[]'::jsonb)) = 0
       and jsonb_array_length(coalesce(NEW.phone_jsonb, '[]'::jsonb)) = 0
    then return NEW; end if;
    v_weight := public.resolve_source_weight(NEW.lead_source);
    perform public.emit_score_event(
        NEW.sales_id, 'sales', 'sales.contact_created_qualified',
        'contact', NEW.id, 2, v_weight,
        'sales.contact_created_qualified:contact:' || NEW.id
    );
    return NEW;
end;
$$;

create or replace function public.score_on_contact_status_change() returns trigger language plpgsql as $$
declare
    v_rule text;
    v_pts  numeric;
begin
    if NEW.sales_id is null then return NEW; end if;
    v_rule := case
        when OLD.status = 'cold' and NEW.status = 'warm'        then 'sales.contact_status_cold_to_warm'
        when OLD.status = 'warm' and NEW.status = 'hot'         then 'sales.contact_status_warm_to_hot'
        when OLD.status = 'hot'  and NEW.status = 'in-contract' then 'sales.contact_status_hot_to_in_contract'
        else null
    end;
    if v_rule is null then return NEW; end if;
    v_pts := case v_rule
        when 'sales.contact_status_cold_to_warm'       then 2
        when 'sales.contact_status_warm_to_hot'        then 4
        when 'sales.contact_status_hot_to_in_contract' then 6
    end;
    perform public.emit_score_event(
        NEW.sales_id, 'sales', v_rule, 'contact', NEW.id, v_pts, 1.0,
        v_rule || ':contact:' || NEW.id || ':' || coalesce(OLD.status,'null') || ':' || NEW.status
    );
    return NEW;
end;
$$;

create or replace function public.score_on_contact_note_insert() returns trigger language plpgsql as $$
begin
    if NEW.sales_id is null then return NEW; end if;
    if not public.is_meaningful_note(NEW.text, NEW.attachments) then return NEW; end if;
    perform public.emit_score_event(
        NEW.sales_id, 'sales', 'sales.contact_note_meaningful',
        'contact_note', NEW.id, 1, 1.0,
        'sales.contact_note_meaningful:contact_note:' || NEW.id
    );
    return NEW;
end;
$$;

create or replace function public.score_on_task_done() returns trigger language plpgsql as $$
declare
    v_rule text;
    v_pts  numeric;
begin
    if NEW.sales_id is null then return NEW; end if;
    v_rule := case
        when NEW.type in ('email', 'thank-you', 'follow-up') then 'sales.task_done_light'
        when NEW.type in ('call', 'lunch')                   then 'sales.task_done_medium'
        when NEW.type in ('meeting', 'demo', 'ship')         then 'sales.task_done_heavy'
        else 'sales.task_done_light'
    end;
    v_pts := case v_rule
        when 'sales.task_done_light'  then 1
        when 'sales.task_done_medium' then 2
        when 'sales.task_done_heavy'  then 3
    end;
    perform public.emit_score_event(
        NEW.sales_id, 'sales', v_rule, 'task', NEW.id, v_pts, 1.0,
        v_rule || ':task:' || NEW.id
    );
    if NEW.due_date is not null and NEW.done_date::date <= NEW.due_date::date then
        perform public.emit_score_event(
            NEW.sales_id, 'sales', 'sales.task_done_on_time_bonus',
            'task', NEW.id, 1, 1.0,
            'sales.task_done_on_time_bonus:task:' || NEW.id
        );
    end if;
    return NEW;
end;
$$;

create or replace function public.score_on_deal_insert() returns trigger language plpgsql as $$
declare
    v_weight numeric;
begin
    if NEW.sales_id is null then return NEW; end if;
    v_weight := public.resolve_source_weight(NEW.lead_source);
    perform public.emit_score_event(
        NEW.sales_id, 'sales', 'sales.deal_created', 'deal', NEW.id, 4, v_weight,
        'sales.deal_created:deal:' || NEW.id
    );
    return NEW;
end;
$$;

create or replace function public.score_on_deal_stage_change() returns trigger language plpgsql as $$
declare
    v_rule   text;
    v_pts    numeric;
    v_weight numeric;
begin
    if NEW.sales_id is null then return NEW; end if;
    v_rule := case NEW.stage
        when 'proposal-sent'  then 'sales.deal_stage_proposal_sent'
        when 'in-negociation' then 'sales.deal_stage_in_negociation'
        when 'won'            then 'sales.deal_stage_won'
        when 'delayed'        then 'sales.deal_stage_delayed'
        else null
    end;
    if v_rule is null then return NEW; end if;
    v_weight := public.resolve_source_weight(NEW.lead_source);
    v_pts := case v_rule
        when 'sales.deal_stage_proposal_sent'  then  5
        when 'sales.deal_stage_in_negociation' then  7
        when 'sales.deal_stage_won'            then 20
        when 'sales.deal_stage_delayed'        then -2
    end;
    if v_rule = 'sales.deal_stage_won' then
        perform public.emit_score_event(
            NEW.sales_id, 'sales', v_rule, 'deal', NEW.id,
            v_pts, greatest(0.6, v_weight), v_rule || ':deal:' || NEW.id
        );
        if NEW.amount is not null and NEW.amount > 0 then
            perform public.emit_score_event(
                NEW.sales_id, 'sales', 'sales.deal_won_amount_bonus', 'deal', NEW.id,
                floor(NEW.amount::numeric / 5000), greatest(0.6, v_weight),
                'sales.deal_won_amount_bonus:deal:' || NEW.id
            );
        end if;
    elsif v_rule = 'sales.deal_stage_delayed' then
        perform public.emit_score_event(
            NEW.sales_id, 'sales', v_rule, 'deal', NEW.id, v_pts, 1.0,
            v_rule || ':deal:' || NEW.id || ':' || to_char(now(), 'YYYY-MM')
        );
    else
        perform public.emit_score_event(
            NEW.sales_id, 'sales', v_rule, 'deal', NEW.id,
            v_pts, greatest(0.6, v_weight), v_rule || ':deal:' || NEW.id
        );
    end if;
    return NEW;
end;
$$;

create or replace function public.score_on_dev_task_done() returns trigger language plpgsql as $$
declare
    v_pts numeric;
begin
    if NEW.assignee_id is null then return NEW; end if;
    v_pts := case NEW.priority
        when 'urgent' then 13
        when 'high'   then  8
        when 'medium' then  5
        when 'low'    then  3
        else 1
    end;
    perform public.emit_score_event(
        NEW.assignee_id, 'delivery', 'delivery.devtask_done_' || NEW.priority,
        'dev_task', NEW.id, v_pts, 1.0,
        'delivery.devtask_done:dev_task:' || NEW.id
    );
    if NEW.due_date is not null and current_date <= NEW.due_date then
        perform public.emit_score_event(
            NEW.assignee_id, 'delivery', 'delivery.devtask_done_on_time_bonus',
            'dev_task', NEW.id, 2, 1.0,
            'delivery.devtask_done_on_time_bonus:dev_task:' || NEW.id
        );
    end if;
    if NEW.deal_id is not null then
        perform public.emit_score_event(
            NEW.assignee_id, 'delivery', 'delivery.devtask_linked_to_deal_bonus',
            'dev_task', NEW.id, 3, 1.0,
            'delivery.devtask_linked_to_deal_bonus:dev_task:' || NEW.id
        );
    end if;
    if NEW.contact_id is not null or NEW.company_id is not null then
        perform public.emit_score_event(
            NEW.assignee_id, 'delivery', 'delivery.devtask_linked_to_business_bonus',
            'dev_task', NEW.id, 2, 1.0,
            'delivery.devtask_linked_to_business_bonus:dev_task:' || NEW.id
        );
    end if;
    return NEW;
end;
$$;

create or replace function public.score_on_dev_task_reopened() returns trigger language plpgsql as $$
declare
    v_prev  numeric;
    v_actor bigint;
begin
    v_actor := coalesce(NEW.assignee_id, OLD.assignee_id);
    if v_actor is null then return NEW; end if;
    select coalesce(sum(raw_points), 0) into v_prev
    from public.score_events
    where entity_type = 'dev_task' and entity_id = NEW.id
      and domain = 'delivery' and rule_code not like '%reopen%';
    if v_prev > 0 then
        perform public.emit_score_event(
            v_actor, 'delivery', 'delivery.devtask_reopen_penalty',
            'dev_task', NEW.id, -round(v_prev * 0.5, 2), 1.0,
            'delivery.devtask_reopen_penalty:dev_task:' || NEW.id || ':' || extract(epoch from now())::bigint
        );
    end if;
    return NEW;
end;
$$;

-- 7. Attach scoring triggers
create or replace trigger score_company_insert
    after insert on public.companies
    for each row execute function public.score_on_company_insert();

create or replace trigger score_contact_insert
    after insert on public.contacts
    for each row execute function public.score_on_contact_insert();

create or replace trigger score_contact_status_change
    after update on public.contacts
    for each row
    when (old.status is distinct from new.status)
    execute function public.score_on_contact_status_change();

create or replace trigger score_contact_note_insert
    after insert on public.contact_notes
    for each row execute function public.score_on_contact_note_insert();

create or replace trigger score_task_done
    after update on public.tasks
    for each row
    when (old.done_date is null and new.done_date is not null)
    execute function public.score_on_task_done();

create or replace trigger score_deal_insert
    after insert on public.deals
    for each row execute function public.score_on_deal_insert();

create or replace trigger score_deal_stage_change
    after update on public.deals
    for each row
    when (old.stage is distinct from new.stage)
    execute function public.score_on_deal_stage_change();

create or replace trigger score_dev_task_done
    after update on public.dev_tasks
    for each row
    when (old.status <> 'done' and new.status = 'done')
    execute function public.score_on_dev_task_done();

create or replace trigger score_dev_task_reopened
    after update on public.dev_tasks
    for each row
    when (old.status = 'done' and new.status <> 'done')
    execute function public.score_on_dev_task_reopened();

-- 8. Management scoreboard view
create or replace view public.management_scoreboard with (security_invoker = on) as
select
    s.id                                                              as sales_id,
    s.first_name,
    s.last_name,
    s.email,
    s.avatar,
    coalesce(sum(se.points) filter (
        where se.domain = 'sales'
          and se.period_day >= date_trunc('month', current_date)::date
    ), 0)                                                             as sales_score_month,
    coalesce(sum(se.points) filter (
        where se.domain = 'delivery'
          and se.period_day >= date_trunc('month', current_date)::date
    ), 0)                                                             as delivery_score_month,
    coalesce(sum(se.points) filter (
        where se.period_day >= date_trunc('month', current_date)::date
    ), 0)                                                             as total_score_month,
    coalesce(sum(se.points) filter (
        where se.period_day >= date_trunc('month', current_date - interval '1 month')::date
          and se.period_day <  date_trunc('month', current_date)::date
    ), 0)                                                             as total_score_prev_month,
    coalesce(sum(se.points), 0)                                       as total_score_all_time
from public.sales s
left join public.score_events se on se.sales_id = s.id
where s.disabled = false
group by s.id, s.first_name, s.last_name, s.email, s.avatar;

-- 9. Grant on the view (PostgREST requires explicit grants on views)
grant select on public.management_scoreboard to anon;
grant select on public.management_scoreboard to authenticated;
grant select on public.management_scoreboard to service_role;

-- 10. Default score targets
insert into public.score_targets (domain, period, target_score) values
    ('sales',    'month', 120),
    ('delivery', 'month', 100),
    ('sales',    'week',   30),
    ('delivery', 'week',   25)
on conflict (domain, period) do nothing;
