-- Email sync: tables for IMAP email synchronization

-- Use pgcrypto for password encryption
create extension if not exists "pgcrypto" with schema "extensions";

create table public.email_accounts (
    id bigint generated by default as identity primary key,
    email extensions.citext not null unique,
    imap_host text not null,
    imap_port integer not null default 993,
    smtp_host text,
    smtp_port integer not null default 465,
    encrypted_password text not null,
    sales_id bigint,
    is_active boolean not null default true,
    skip_tls_verify boolean not null default false,
    created_at timestamp with time zone not null default now()
);

alter table public.email_accounts
    add constraint email_accounts_sales_id_fkey foreign key (sales_id) references public.sales(id);

create table public.email_messages (
    id bigint generated by default as identity primary key,
    message_id text not null,
    email_account_id bigint not null,
    folder text not null,
    from_email text not null,
    from_name text,
    to_emails jsonb,
    cc_emails jsonb,
    subject text,
    text_body text,
    html_body text,
    date timestamp with time zone not null,
    is_read boolean not null default false,
    contact_id bigint,
    sales_id bigint,
    uid integer,
    created_at timestamp with time zone not null default now(),
    unique(email_account_id, folder, message_id)
);

alter table public.email_messages
    add constraint email_messages_email_account_id_fkey foreign key (email_account_id) references public.email_accounts(id) on delete cascade;
alter table public.email_messages
    add constraint email_messages_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete set null;
alter table public.email_messages
    add constraint email_messages_sales_id_fkey foreign key (sales_id) references public.sales(id);

create index email_messages_email_account_id_idx on public.email_messages using btree (email_account_id);
create index email_messages_contact_id_idx on public.email_messages using btree (contact_id);
create index email_messages_date_idx on public.email_messages using btree (date desc);
create index email_messages_is_read_idx on public.email_messages using btree (is_read) where is_read = false;
create index email_messages_message_id_idx on public.email_messages using btree (message_id);

create table public.email_sync_state (
    id bigint generated by default as identity primary key,
    email_account_id bigint not null,
    folder text not null,
    last_uid integer not null default 0,
    last_sync timestamp with time zone,
    unique(email_account_id, folder)
);

alter table public.email_sync_state
    add constraint email_sync_state_email_account_id_fkey foreign key (email_account_id) references public.email_accounts(id) on delete cascade;

-- RLS
alter table public.email_accounts enable row level security;
create policy "Enable read for authenticated" on public.email_accounts for select to authenticated using (true);
create policy "Enable insert for admins" on public.email_accounts for insert to authenticated with check (public.is_admin());
create policy "Enable update for admins" on public.email_accounts for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "Enable delete for admins" on public.email_accounts for delete to authenticated using (public.is_admin());

alter table public.email_messages enable row level security;
create policy "Enable read access for authenticated users" on public.email_messages for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.email_messages for insert to authenticated with check (true);
create policy "Email Messages Update Policy" on public.email_messages for update to authenticated using (true);
create policy "Email Messages Delete Policy" on public.email_messages for delete to authenticated using (true);

alter table public.email_sync_state enable row level security;
create policy "Enable read for authenticated" on public.email_sync_state for select to authenticated using (true);
create policy "Enable insert for service role" on public.email_sync_state for insert to service_role with check (true);
create policy "Enable update for service role" on public.email_sync_state for update to service_role using (true);

-- Grants
grant all on table public.email_accounts to anon;
grant all on table public.email_accounts to authenticated;
grant all on table public.email_accounts to service_role;

grant all on table public.email_messages to anon;
grant all on table public.email_messages to authenticated;
grant all on table public.email_messages to service_role;

grant all on table public.email_sync_state to anon;
grant all on table public.email_sync_state to authenticated;
grant all on table public.email_sync_state to service_role;

grant all on sequence public.email_accounts_id_seq to anon;
grant all on sequence public.email_accounts_id_seq to authenticated;
grant all on sequence public.email_accounts_id_seq to service_role;

grant all on sequence public.email_messages_id_seq to anon;
grant all on sequence public.email_messages_id_seq to authenticated;
grant all on sequence public.email_messages_id_seq to service_role;

grant all on sequence public.email_sync_state_id_seq to anon;
grant all on sequence public.email_sync_state_id_seq to authenticated;
grant all on sequence public.email_sync_state_id_seq to service_role;

-- Helper function to encrypt/decrypt passwords using a server-side key
create or replace function public.encrypt_email_password(plain_password text)
returns text
language plpgsql security definer
set search_path to ''
as $$
declare
    encryption_key text;
begin
    encryption_key := current_setting('app.settings.email_encryption_key', true);
    if encryption_key is null or encryption_key = '' then
        raise exception 'Email encryption key not configured';
    end if;
    return encode(
        extensions.pgp_sym_encrypt(plain_password, encryption_key),
        'base64'
    );
end;
$$;

create or replace function public.decrypt_email_password(encrypted_password text)
returns text
language plpgsql security definer
set search_path to ''
as $$
declare
    encryption_key text;
begin
    encryption_key := current_setting('app.settings.email_encryption_key', true);
    if encryption_key is null or encryption_key = '' then
        raise exception 'Email encryption key not configured';
    end if;
    return extensions.pgp_sym_decrypt(
        decode(encrypted_password, 'base64'),
        encryption_key
    );
end;
$$;

-- Encryption function is callable by authenticated users (so admins can save
-- accounts from the UI). Writes to email_accounts are still gated by the
-- is_admin() RLS policy. Decryption stays service_role-only (sync worker / edge).
-- We explicitly revoke from anon/authenticated because the schema's default
-- privileges auto-grant all functions to those roles.
revoke all on function public.encrypt_email_password(text) from public;
revoke all on function public.encrypt_email_password(text) from anon;
grant execute on function public.encrypt_email_password(text) to authenticated;
grant execute on function public.encrypt_email_password(text) to service_role;

revoke all on function public.decrypt_email_password(text) from public;
revoke all on function public.decrypt_email_password(text) from anon;
revoke all on function public.decrypt_email_password(text) from authenticated;
grant execute on function public.decrypt_email_password(text) to service_role;

-- Unread emails summary view for dashboard
create or replace view public.unread_emails_summary with (security_invoker = on) as
select
    em.id,
    em.from_email,
    em.from_name,
    em.subject,
    em.date,
    em.contact_id,
    em.sales_id,
    em.email_account_id,
    ea.email as account_email,
    c.first_name as contact_first_name,
    c.last_name as contact_last_name
from public.email_messages em
join public.email_accounts ea on ea.id = em.email_account_id
left join public.contacts c on c.id = em.contact_id
where em.is_read = false
  and em.folder = 'INBOX'
order by em.date desc;

grant all on table public.unread_emails_summary to anon;
grant all on table public.unread_emails_summary to authenticated;
grant all on table public.unread_emails_summary to service_role;
