-- User actions telemetry: low-noise events used to (a) understand workflows
-- and (b) bootstrap agent skills from real human sequences.
-- Captured on the frontend (dataProvider wrapper + navigation hook) and ingested
-- in batch via the record-actions edge function.

create table public.user_actions (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    session_id text not null,
    occurred_at timestamptz not null default now(),
    action text not null,
    resource text,
    resource_id text,
    payload jsonb not null default '{}'::jsonb,
    context jsonb not null default '{}'::jsonb,
    client_info jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    constraint user_actions_action_format
        check (action ~ '^[a-z][a-z0-9_.]{1,63}$'),
    constraint user_actions_session_format
        check (length(session_id) between 8 and 64)
);

create index user_actions_user_occurred_idx
    on public.user_actions (user_id, occurred_at desc);

create index user_actions_session_idx
    on public.user_actions (session_id, occurred_at);

create index user_actions_action_idx
    on public.user_actions (action, occurred_at desc);

-- TTL: actions older than 30 days are not load-bearing for skill suggestion.
-- A nightly cron (out of scope here) can run the cleanup function below.
create or replace function public.cleanup_user_actions(p_days int default 30)
returns int language plpgsql security definer set search_path = public as $$
declare
    deleted_count int;
begin
    delete from public.user_actions
     where occurred_at < now() - (p_days || ' days')::interval;
    get diagnostics deleted_count = row_count;
    return deleted_count;
end;
$$;

alter table public.user_actions enable row level security;

-- Users see their own actions; admins (sales.administrator) see all.
create policy user_actions_select
    on public.user_actions for select
    to authenticated
    using (
        user_id = auth.uid()
        or exists (
            select 1 from public.sales s
             where s.user_id = auth.uid()
               and coalesce(s.administrator, false)
        )
    );

-- Users insert only as themselves. The edge function uses service-role and
-- bypasses RLS for batch ingest.
create policy user_actions_insert_self
    on public.user_actions for insert
    to authenticated
    with check (user_id = auth.uid());

grant select, insert on public.user_actions to authenticated;
grant all on public.user_actions to service_role;

-- View: session summary for the UI (one row per session with bounds + count).
create or replace view public.user_action_sessions
with (security_invoker = on) as
select
    user_id,
    session_id,
    min(occurred_at) as started_at,
    max(occurred_at) as ended_at,
    count(*) as action_count,
    count(distinct action) as distinct_actions,
    array_agg(distinct resource) filter (where resource is not null) as resources_touched
  from public.user_actions
 group by user_id, session_id;

grant select on public.user_action_sessions to authenticated;
