-- Dev tasks: Linear-style Kanban board for internal engineering tickets.

create table public.dev_tasks (
    id bigint generated by default as identity primary key,
    title text not null,
    description text,
    status text not null default 'backlog',
    priority text not null default 'none',
    "index" smallint not null default 0,
    assignee_id bigint,
    due_date date,
    label_ids bigint[] not null default '{}',
    contact_id bigint,
    company_id bigint,
    deal_id bigint,
    archived_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

alter table public.dev_tasks
    add constraint dev_tasks_assignee_id_fkey foreign key (assignee_id) references public.sales(id) on delete set null;
alter table public.dev_tasks
    add constraint dev_tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on delete set null;
alter table public.dev_tasks
    add constraint dev_tasks_company_id_fkey foreign key (company_id) references public.companies(id) on delete set null;
alter table public.dev_tasks
    add constraint dev_tasks_deal_id_fkey foreign key (deal_id) references public.deals(id) on delete set null;

create index dev_tasks_status_index_idx on public.dev_tasks using btree (status, "index" desc);
create index dev_tasks_assignee_id_idx on public.dev_tasks using btree (assignee_id);
create index dev_tasks_archived_at_idx on public.dev_tasks using btree (archived_at);

create table public.dev_task_labels (
    id bigint generated by default as identity primary key,
    name text not null unique,
    color text not null default '#64748b',
    created_at timestamp with time zone not null default now()
);

-- Trigger to keep updated_at in sync.
create or replace function public.dev_tasks_set_updated_at() returns trigger
language plpgsql as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create trigger dev_tasks_updated_at
    before update on public.dev_tasks
    for each row execute function public.dev_tasks_set_updated_at();

-- RLS: authenticated users have full access (same posture as tasks/deals).
alter table public.dev_tasks enable row level security;
create policy "Enable read access for authenticated users" on public.dev_tasks
    for select to authenticated using (true);
create policy "Enable insert for authenticated users" on public.dev_tasks
    for insert to authenticated with check (true);
create policy "Enable update for authenticated users" on public.dev_tasks
    for update to authenticated using (true) with check (true);
create policy "Enable delete for authenticated users" on public.dev_tasks
    for delete to authenticated using (true);

alter table public.dev_task_labels enable row level security;
create policy "Enable read access for authenticated users" on public.dev_task_labels
    for select to authenticated using (true);
create policy "Enable insert for authenticated users" on public.dev_task_labels
    for insert to authenticated with check (true);
create policy "Enable update for authenticated users" on public.dev_task_labels
    for update to authenticated using (true) with check (true);
create policy "Enable delete for authenticated users" on public.dev_task_labels
    for delete to authenticated using (true);

grant all on table public.dev_tasks to anon;
grant all on table public.dev_tasks to authenticated;
grant all on table public.dev_tasks to service_role;
grant all on table public.dev_task_labels to anon;
grant all on table public.dev_task_labels to authenticated;
grant all on table public.dev_task_labels to service_role;
grant all on sequence public.dev_tasks_id_seq to anon;
grant all on sequence public.dev_tasks_id_seq to authenticated;
grant all on sequence public.dev_tasks_id_seq to service_role;
grant all on sequence public.dev_task_labels_id_seq to anon;
grant all on sequence public.dev_task_labels_id_seq to authenticated;
grant all on sequence public.dev_task_labels_id_seq to service_role;

-- Seed labels.
insert into public.dev_task_labels (name, color) values
    ('bug', '#ef4444'),
    ('feature', '#3b82f6'),
    ('tech', '#8b5cf6'),
    ('ui', '#ec4899'),
    ('backend', '#10b981'),
    ('urgent', '#f97316')
on conflict (name) do nothing;
