-- Appointments and contact recordings (calendar + call recording features)
-- Idempotent: safe to run even if objects already exist.

create table if not exists public.appointments (
    id bigint generated by default as identity primary key,
    contact_id bigint,
    title text not null,
    description text,
    start_at timestamp with time zone not null,
    end_at timestamp with time zone not null,
    location text,
    source text not null default 'manual',
    status text not null default 'scheduled',
    sales_id bigint,
    created_at timestamp with time zone not null default now()
);

create index if not exists appointments_contact_id_idx on public.appointments using btree (contact_id);
create index if not exists appointments_start_at_idx on public.appointments using btree (start_at);
create index if not exists appointments_sales_id_idx on public.appointments using btree (sales_id);

do $$ begin
    alter table public.appointments
        add constraint appointments_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete set null;
exception when duplicate_object then null; end $$;

do $$ begin
    alter table public.appointments
        add constraint appointments_sales_id_fkey foreign key (sales_id) references public.sales(id);
exception when duplicate_object then null; end $$;

create table if not exists public.contact_recordings (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    storage_path text not null,
    duration_seconds integer,
    transcription text,
    transcription_status text not null default 'pending',
    summary text,
    email_advice text,
    sms_advice text,
    created_at timestamp with time zone not null default now(),
    sales_id bigint
);

create index if not exists contact_recordings_contact_id_idx on public.contact_recordings using btree (contact_id);

do $$ begin
    alter table public.contact_recordings
        add constraint contact_recordings_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;
exception when duplicate_object then null; end $$;

do $$ begin
    alter table public.contact_recordings
        add constraint contact_recordings_sales_id_fkey foreign key (sales_id) references public.sales(id);
exception when duplicate_object then null; end $$;

-- Triggers: default sales_id to current user
create or replace trigger set_contact_recordings_sales_id_trigger
    before insert on public.contact_recordings
    for each row execute function public.set_sales_id_default();

create or replace trigger set_appointments_sales_id_trigger
    before insert on public.appointments
    for each row execute function public.set_sales_id_default();

-- RLS
alter table public.appointments enable row level security;
drop policy if exists "Enable read access for authenticated users" on public.appointments;
create policy "Enable read access for authenticated users" on public.appointments for select to authenticated using (true);
drop policy if exists "Enable insert for authenticated users only" on public.appointments;
create policy "Enable insert for authenticated users only" on public.appointments for insert to authenticated with check (true);
drop policy if exists "Appointment Update Policy" on public.appointments;
create policy "Appointment Update Policy" on public.appointments for update to authenticated using (true);
drop policy if exists "Appointment Delete Policy" on public.appointments;
create policy "Appointment Delete Policy" on public.appointments for delete to authenticated using (true);

alter table public.contact_recordings enable row level security;
drop policy if exists "Enable read access for authenticated users" on public.contact_recordings;
create policy "Enable read access for authenticated users" on public.contact_recordings for select to authenticated using (true);
drop policy if exists "Enable insert for authenticated users only" on public.contact_recordings;
create policy "Enable insert for authenticated users only" on public.contact_recordings for insert to authenticated with check (true);
drop policy if exists "Contact Recordings Update Policy" on public.contact_recordings;
create policy "Contact Recordings Update Policy" on public.contact_recordings for update to authenticated using (true);
drop policy if exists "Contact Recordings Delete Policy" on public.contact_recordings;
create policy "Contact Recordings Delete Policy" on public.contact_recordings for delete to authenticated using (true);

-- Grants
grant all on table public.appointments to anon, authenticated, service_role;
grant all on table public.contact_recordings to anon, authenticated, service_role;
grant all on sequence public.appointments_id_seq to anon, authenticated, service_role;
grant all on sequence public.contact_recordings_id_seq to anon, authenticated, service_role;
